site_name: Duik Documentation
site_url: http://rainboxlab.org
repo_url: http://duik-docs.rainboxlab.org
edit_uri: https://github.com/Rainbox-dev/DuAEF_Duik_Docs/tree/master/src/docs/
site_description: The Duik comprehensive documentation
site_author: Nicolas Dufresne and contributors
copyright: 'Copyright © 2018-2020 Rainbox Productions and Nicolas Dufresne'
use_directory_urls: false
theme:
    name: readthedocs
    custom_dir: theme/
markdown_extensions:
    - smarty
    - footnotes
    - tables
    - admonition
    - codehilite
    - fenced_code
    - toc
extra_css:
    - style.css
    - video.css
extra_javascript:
    - video.js
site_dir: ../docs/
dev_addr: '127.0.0.1:8001'
extra:
    version: 16.2.9
nav:
    - Home: index.md
    - Tutorials: tutorials.md
    - Printed User Guide: printed-user-guide.md
    - Introduction:
        - Preamble: preamble.md
        - DuAEF: duaef.md
        - Should I use Duik?: should-i-use-duik.md
        - Contribution: contributing-guide.md
        - Bassel: bassel.md
        - User License: license.md
        - Be Annoying!: be-annoying.md
    - Installation: install-duik.md
    - First look:
        - Introduction: first-look-at-duik.md
        - Duik Cmd: duik-cmd.md
    - Notes editor: notes-editor.md
    - Contextual help: contextual-help.md
    - Performance: performance.md
    - Rigging:
        - Introduction: rigging.md
        - Structures:
            - Introduction: structures.md
            - Create Structures: create-structures.md
            - Structure Tools: structure-tools.md
        - Constraints:
            - Introduction: constraints.md
            - Autorig & IK: autorig.md
            - Connector: connector.md
            - Animation Blender: animation-blender-setup.md
            - Bones: bones.md
            - Auto-Parent: auto-parent.md
            - Parent Constraint: parent-constraint.md
            - Parent Accross Comps: parent-accross-compositions.md
            - Path Constraint: path-constraint.md
            - Position Constraint: position-constraint.md
            - Orientation Constraint: orientation-constraint.md
            - List: duik-list.md
            - Expose Transform: expose-transform.md
            - Zero: zero.md
            - Lock Property: lock-property.md
            - Separate Dimensions: separate-dimensions.md
        - Controllers:
            - Introduction: controllers.md
            - Controller Tools: controller-tools.md
    - Automations:
        - Introduction: automations.md
        - Blink: blink.md
        - Effector: effector.md
        - Effector Map: effector-map.md
        - Kleaner: kleaner.md
        - List: duik-list.md
        - Looper: looper.md
        - Motion Trail: motion-trail.md
        - Move Away: move-away.md
        - Paint Rig: paint-rig.md
        - Random: random.md
        - Separate Dimensions: separate-dimensions.md
        - Spring: kleaner.md
        - Swing: swing.md
        - Time Remap: time-remap.md
        - Walk Cycle: walk-cycle.md
        - Wheel: wheel.md
        - Wiggle: wiggle.md
        - X-Sheet: x-sheet.md
    - Animation:
        - Introduction: animation.md
        - Kleaner: kleaner.md
        - Copy/Paste: copy-paste-animation.md
        - Keyframe Tools: keyframe-tools.md
        - IK/FK Switch: ik-fk-switch.md
        - Animation Blender: animation-blender.md
        - Motion Trail: motion-trail.md
        - Cel Animation: cel-animation.md
    - Camera:
        - Introduction: camera.md
        - Camera Rig: camera-rig.md
        - Scale Z-Link: scale-z-link.md
        - 2D Camera: camera-2d.md
        - Framing Guides: duframe.md
    - Tools: rigging-tools.md
    - Settings: settings.md
    - Development:
        - The Duik API: duik-api.md
        - The Duduf After Effects Framework: duaef.md
    - F.A.Q.: duik-faq.md
    - Changelog: duik-16-changelog.md
    - License:
        - GNU GPLv3: gnu-gpl.md
        - Documentation license: doc-license.md
    - Credits: credits.md
    - Contact: https://rainboxlab.org/about/contact/
    - Donate: https://rainboxlab.org/about/donate/
